### ISSUE TITLE
RPI 2b Compilation Issues

### ISSUE THREAD

**Issue by vgthecoder** [gonzalop/wombatt#16]
I get this error when trying to do `make`
```
ERRO Running error: 1 error occurred:
	* can't run linter goanalysis_metalinter: goanalysis_metalinter: shift: package "modbus" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference
	make: *** [Makefile:101: golangci-lint-run] Error 3

**Comment by gonzalop** [comment]
I haven't see that one before. It could be an old golangci-list.

Can you run `go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.59.1`? I'll update the Makefile help text to this version if it works for you.

Thanks!

**Comment by vgthecoder** [comment]
Thank you, That worked perfectly!
