### ISSUE TITLE
Feature Request: Connect to EG4 battery using Bluetooth

### ISSUE THREAD

**Issue by k3vmcd** [gonzalop/wombatt#8]

**Comment by gonzalop** [comment]
What kind of device do you use to go from RS485 to bluetooth?

**Comment by k3vmcd** [comment]
I have two of these EG4 12V 400AH which have built-in bluetooth https://signaturesolar.com/eg4-lifepower4-lithium-battery-12v-400ah/

They show up with 10 digit names in the format Z122000###.

I am able to connect over bluetooth and view the same stats that BMS Tools on the wired jack outputs using this Android app: https://play.google.com/store/apps/details?id=com.eg4.monitor

**Comment by gonzalop** [comment]
Is there any information available on the protocol used?

It would be a lot easier to get [https://www.amazon.com/PUSR-USR-TCP232-304-Ethernet-Converter-Supported/dp/B09DCT1YDR/](https://www.amazon.com/PUSR-USR-TCP232-304-Ethernet-Converter-Supported/dp/B09DCT1YDR/), connect it to the first battery and then have wombatt query the device using Modbus over TCP (see https://github.com/gonzalop/wombatt/issues/3 for screenshots of the configuration used for the device, and example command line arguments for wombatt)
